### ISSUE TITLE
Trying Doxygen on MacOS with the example provided

### ISSUE THREAD

**Issue by amaged** [Anvil/bash-doxygen#17]
Hi, I tried to run doxygen for bash on the example provided but the html generated is empty, I am using GNU Sed.

Attached all the below files:
1) Doxygen output from the console
2) Doxyfile
3) Example file : ex.sh
4) Output html folder

[Archive.zip](https://github.com/Anvil/bash-doxygen/files/2215142/Archive.zip)

Cumulus-AT1176:~ ahmed$ /usr/local/bin/sed --version
/usr/local/bin/sed (GNU sed) 4.5
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
Cumulus-AT1176:~ ahmed$ uname -a
Darwin Cumulus-AT1176 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by Anvil** [comment]
Thanks for the report, I'll dig into that soon.

**Comment by Anvil** [comment]
OK, first conclusion, it's not about your script, neither about the filter itself. It has to do with your Doxyfile. I'm not confident with my doxygen configuration skills, but I'll keep digging.

**Comment by Anvil** [comment]
I see, obvious. The shebang in the `doxygen-bash.sed` file is `#!/usr/bin/sed`, while your sed installation has put the binary as `/usr/local/bin/sed`. Change the path in the filter according to your installation.
