### ISSUE TITLE
Detect functions

### ISSUE THREAD

**Issue by useronkel** [Anvil/bash-doxygen#2]
Hi.
Great sed job :-)
Anyway, the detection of functions is inconsistent...

bash allows following function definitions:
: funcname() {
: function funcname() {
: function namespace::funcname() {

Is it possible to reflect this in the script?

**Comment by Anvil** [comment]
That https://github.com/Anvil/bash-doxygen/compare/c8bd22ee0839be80c771eb5e65281b654abdae9d...master should do the trick

Good for you ?

**Comment by Anvil** [comment]
I'll take that a as yes.
