### ISSUE TITLE
Functions not detected OSX El Cap (probably BSDs as well)

### ISSUE THREAD

**Issue by charlesdaniels** [Anvil/bash-doxygen#6]
Tested on OSX 10.11.6. 

Functions are not detected correctly on Mac OSX. This is because OSX uses BSD `sed`. This will probably affect BSD OSes also, considering this. To reproduce, just run the unit test on a mac. 

The workaround I have found is to [install `gnu-sed` via homebrew](http://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x), then use `gsed` instead of `sed` in `Doxyfile`. 

Not sure if you want to support both versions of `sed`, but it might be helpful to others to make note of this workaround in the README.

**Comment by Anvil** [comment]
I will make a note about it in the README.md, thank you for reporting this. I don't think I will support other versions of sed for now, mainly because I don't have time for that. And other versions of sed.

If you have some patches to fix the compatibility, though, feel free to submit them.
